clusterName: YOURCLUSTERHERE
splunkObservability:
  realm: YOURREALMHERE
  accessToken: YOURTOKENHERE

fluentd:
  config:
    containers:
      logFormatType: cri
      criTimeFormat: "%Y-%m-%dT%H:%M:%S.%NZ"