clusterName: YOURCLUSTERHERE
splunkObservability.realm: YOURREALMHERE        
splunkObservability.accessToken: YOURTOKENHERE

fluentd:
  config:
    containers:
      logFormatType: cri
      criTimeFormat: "%Y-%m-%dT%H:%M:%S.%NZ"